### ISSUE TITLE
Windows: Installing “linter-api-blueprint@0.2.0” failed

### ISSUE THREAD

**Issue by ghost** [zdne/linter-api-blueprint#1] opened 2016-01-26 14:09 UTC
Hello, i'm having an install issue.  Any suggestions?

> protagonist@1.2.5 install C:\Temp\apm-install-dir-116026-7296-rtwuth\node_modules\linter-api-blueprint\node_modules\protagonist
> node-gyp rebuild

C:\Temp\apm-install-dir-116026-7296-rtwuth\node_modules\linter-api-blueprint\node_modules\protagonist>if not defined npm_config_node_gyp (node "C:\Users\206475655\AppData\Local\atom\app-1.4.1\resources\app\apm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

npm WARN engine refract-query@0.0.1: wanted: {"node":"5.1.x","npm":"3.3.x"} (current: {"node":"0.10.40","npm":"2.13.3"})
gypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Users\206475655\AppData\Local\atom\app-1.4.1\resources\app\apm\bin\node.exe" "C:\Users\206475655\AppData\Local\atom\app-1.4.1\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\206475655\.atom\.apm\.apmrc" "--userconfig" "C:\Users\206475655\.atom\.apmrc" "install" "C:\Temp\d-116026-7296-1mjo1m1\package.tgz" "--target=0.34.5" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! protagonist@1.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the protagonist@1.2.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above.

**Comment by zdne** [comment] 2016-01-27 12:32
The problem is in the upstream at https://github.com/apiaryio/protagonist/issues/121

**Comment by zdne** [comment] 2016-01-27 12:33
Possible solution is replace the protagonist dependency with the `drafter.js` once https://github.com/apiaryio/drafter/pull/220 is merged.

**Comment by simobest13** [comment] 2016-03-01 20:53
How can I solve this problems?

**Comment by zdne** [comment] 2016-03-02 09:05
@simobest13 are you running Visual Studio 2015?

**Comment by zdne** [comment] 2016-03-02 09:13
@simobest13 if so, check https://github.com/apiaryio/protagonist/issues/121#issuecomment-187700234

**Closed as completed** 2016-03-02 09:13 UTC
